export const PRIVACY_PARAGRAPHS = [
  'RailMitra helps two willing passengers coordinate a voluntary seat exchange. It is not affiliated with Indian Railways or IRCTC and does not verify tickets or change reservations.',
  'No phone number, name, PNR, payment information or account password is requested. A random installation signing key is created in the operating system secure storage. Its public identifier is shared with offers to verify their origin. This identifies an installation, not a verified passenger.',
  'Posting shares your installation public identifier, train number, service date, coach, seat, berth preferences, class and boarding/destination station codes with nearby app users and the configured cloud service when available. Nearby users may relay these signed offers. Do not publish details you do not want other passengers to see.',
  'Nearby discovery uses Google Nearby Connections over Bluetooth and Wi-Fi. Android location/nearby permissions are requested for this feature. This release does not read or upload GPS coordinates and does not monitor location in the background. Keep the swap screen open for discovery and updates. Google Play services may process diagnostic and device information under Google’s privacy policy.',
  'Offer history, the retry queue and the block list are stored locally in AsyncStorage, which is not encrypted storage. Only the signing key uses secure storage. Offers expire after six hours. Signed offer snapshots and cancellation records are retained locally for up to 24 hours and removed on the next app operation. The server removes these records after 24 hours through an hourly cleanup job.',
  'Delete app data in Settings requests cloud deletion before discarding the installation key. An internet connection is required when cloud data may exist. The server retains a public identifier tombstone for 24 hours to reject replay of old offers. Previously delivered copies on other phones cannot be remotely erased; they expire under the same retention rules. Do not clear Android app storage as a substitute for in-app cloud deletion.',
  'Reports contain only the reporter and reported installation identifiers and a timestamp; there is no free-text chat. Reports expire after 30 days through hourly cleanup. Blocking hides that installation on your phone. Report submission requires internet; the app distinguishes a local block from a submitted report. Moderation blocks can last 30 days.',
  'The application server does not log seat data, message bodies, IP addresses or user-agent strings. It keeps aggregate counts of accepted writes, rejected requests and server failures. The hosting provider and Google Play services may keep their own operational logs; their retention must be reviewed by the developer before publication. No advertising or third-party crash reporting SDK is enabled in this release.',
  'For privacy questions or deletion help, use the developer contact configured in Settings. The developer must publish this policy at a public HTTPS URL and supply verified contact information before release.',
];
export const TERMS_PARAGRAPHS = [
  'RailMitra is a voluntary coordination tool for two passengers. An in-app confirmation does not amend an official reservation or prove ticket ownership. Verify both tickets and follow applicable railway rules and staff instructions before changing seats.',
  'Only post a seat you hold on the specified train service and ticket segment. Do not impersonate another passenger, post false information, harass others, sell seats or demand payment. Report and block suspicious offers. The developer may remove reported offers and block installations for abuse.',
  'Both passengers must independently consent. You may cancel before final completion. Messages may be delayed or unavailable due to connectivity, device settings or nearby participation. Offline agreement is tentative until both phones receive matching signed consent; always confirm directly with the other passenger.',
  'V1 supports direct two-passenger exchanges in SL, 3A, 3E and 2A with identical boarding and destination station codes. It does not provide ticket booking, PNR verification, vacancy prediction, multi-person exchange chains, chat or background alerts.',
  'Keep the screen open and retry if sync fails. Do not move seats solely because another passenger sent a request. An offer expires after six hours; create a new offer when necessary.',
];
