// Localization strings - English
const en = {
    appName: 'RailMitra',
    tagline: 'Your Train Companion',
    searchTitle: 'Find Available Seats',
    trainNumber: 'Train Number',
    trainNumberPlaceholder: 'e.g., 12301',
    journeyDate: 'Journey Date',
    fromStation: 'From Station',
    toStation: 'To Station',
    selectStation: 'Select Station',
    search: 'Search Availability',
    searching: 'Searching...',
    results: 'Results',
    chartStatus: 'Chart Status',
    chartPrepared: 'Chart Prepared',
    chartNotPrepared: 'Chart Not Prepared',
    totalSeats: 'Total Seats',
    vacant: 'Vacant',
    occupied: 'Occupied',
    vacantBerths: 'Vacant Berths',
    coach: 'Coach',
    berth: 'Berth',
    berthType: 'Berth Type',
    from: 'From',
    to: 'To',
    trainRoute: 'Train Route',
    favorites: 'Favorites',
    addToFavorites: 'Add to Favorites',
    removeFromFavorites: 'Remove from Favorites',
    noFavorites: 'No saved favorites yet',
    noResults: 'No results found',
    enterTrainNumber: 'Please enter train number',
    selectStations: 'Please select stations',
    trainNotFound: 'Train not found',
    chartNotReady: 'Chart has not been prepared yet',
    recentSearches: 'Recent Searches',
    availableClasses: 'Available Classes',
    coachDetails: 'Coach Details',
    lowerBerth: 'Lower',
    middleBerth: 'Middle',
    upperBerth: 'Upper',
    sideLower: 'Side Lower',
    sideUpper: 'Side Upper',
    day: 'Day',
    arrives: 'Arrives',
    departs: 'Departs',
    boardingStation: 'Boarding',
    destinationStation: 'Destination',
    language: 'Language',
    settings: 'Settings',
    about: 'About',
    version: 'Version 1.0.0',
    clearAll: 'Clear All',
};

// Hindi - हिन्दी
const hi: typeof en = {
    appName: 'RailMitra',
    tagline: 'आपका ट्रेन साथी',
    searchTitle: 'उपलब्ध सीटें खोजें',
    trainNumber: 'ट्रेन नंबर',
    trainNumberPlaceholder: 'जैसे, 12301',
    journeyDate: 'यात्रा तिथि',
    fromStation: 'कहाँ से',
    toStation: 'कहाँ तक',
    selectStation: 'स्टेशन चुनें',
    search: 'उपलब्धता खोजें',
    searching: 'खोज रहे हैं...',
    results: 'परिणाम',
    chartStatus: 'चार्ट स्थिति',
    chartPrepared: 'चार्ट तैयार',
    chartNotPrepared: 'चार्ट तैयार नहीं',
    totalSeats: 'कुल सीटें',
    vacant: 'खाली',
    occupied: 'भरी हुई',
    vacantBerths: 'खाली बर्थ',
    coach: 'कोच',
    berth: 'बर्थ',
    berthType: 'बर्थ का प्रकार',
    from: 'कहाँ से',
    to: 'कहाँ तक',
    trainRoute: 'ट्रेन मार्ग',
    favorites: 'पसंदीदा',
    addToFavorites: 'पसंदीदा में जोड़ें',
    removeFromFavorites: 'पसंदीदा से हटाएं',
    noFavorites: 'अभी कोई पसंदीदा नहीं',
    noResults: 'कोई परिणाम नहीं मिला',
    enterTrainNumber: 'कृपया ट्रेन नंबर दर्ज करें',
    selectStations: 'कृपया स्टेशन चुनें',
    trainNotFound: 'ट्रेन नहीं मिली',
    chartNotReady: 'चार्ट अभी तैयार नहीं हुआ',
    recentSearches: 'हाल की खोजें',
    availableClasses: 'उपलब्ध श्रेणियाँ',
    coachDetails: 'कोच विवरण',
    lowerBerth: 'निचली',
    middleBerth: 'मध्य',
    upperBerth: 'ऊपरी',
    sideLower: 'साइड निचली',
    sideUpper: 'साइड ऊपरी',
    day: 'दिन',
    arrives: 'आगमन',
    departs: 'प्रस्थान',
    boardingStation: 'चढ़ने का स्टेशन',
    destinationStation: 'गंतव्य',
    language: 'भाषा',
    settings: 'सेटिंग्स',
    about: 'जानकारी',
    version: 'संस्करण 1.0.0',
    clearAll: 'सब मिटाएं',
};

// Tamil - தமிழ்
const ta: typeof en = {
    appName: 'RailMitra',
    tagline: 'உங்கள் ரயில் துணை',
    searchTitle: 'காலி இருக்கைகளை தேடு',
    trainNumber: 'ரயில் எண்',
    trainNumberPlaceholder: 'எ.கா., 12301',
    journeyDate: 'பயண தேதி',
    fromStation: 'எங்கிருந்து',
    toStation: 'எங்கே',
    selectStation: 'நிலையம் தேர்வு',
    search: 'கிடைப்பை தேடு',
    searching: 'தேடுகிறது...',
    results: 'முடிவுகள்',
    chartStatus: 'சார்ட் நிலை',
    chartPrepared: 'சார்ட் தயார்',
    chartNotPrepared: 'சார்ட் தயாராகவில்லை',
    totalSeats: 'மொத்த இருக்கைகள்',
    vacant: 'காலி',
    occupied: 'நிரம்பிய',
    vacantBerths: 'காலி பெர்த்',
    coach: 'பெட்டி',
    berth: 'பெர்த்',
    berthType: 'பெர்த் வகை',
    from: 'எங்கிருந்து',
    to: 'எங்கே',
    trainRoute: 'ரயில் பாதை',
    favorites: 'விருப்பங்கள்',
    addToFavorites: 'விருப்பத்தில் சேர்',
    removeFromFavorites: 'விருப்பத்தை நீக்கு',
    noFavorites: 'விருப்பங்கள் எதுவும் இல்லை',
    noResults: 'முடிவுகள் இல்லை',
    enterTrainNumber: 'ரயில் எண் உள்ளிடவும்',
    selectStations: 'நிலையங்களை தேர்வு செய்யவும்',
    trainNotFound: 'ரயில் கிடைக்கவில்லை',
    chartNotReady: 'சார்ட் இன்னும் தயாராகவில்லை',
    recentSearches: 'சமீபத்திய தேடல்கள்',
    availableClasses: 'கிடைக்கும் வகுப்புகள்',
    coachDetails: 'பெட்டி விவரங்கள்',
    lowerBerth: 'கீழ்',
    middleBerth: 'நடு',
    upperBerth: 'மேல்',
    sideLower: 'பக்க கீழ்',
    sideUpper: 'பக்க மேல்',
    day: 'நாள்',
    arrives: 'வருகை',
    departs: 'புறப்படுகிறது',
    boardingStation: 'ஏறும் நிலையம்',
    destinationStation: 'சேரும் நிலையம்',
    language: 'மொழி',
    settings: 'அமைப்புகள்',
    about: 'பற்றி',
    version: 'பதிப்பு 1.0.0',
    clearAll: 'அழி',
};

// Telugu - తెలుగు
const te: typeof en = {
    appName: 'RailMitra',
    tagline: 'మీ రైలు మిత్రుడు',
    searchTitle: 'ఖాళీ సీట్లు వెతకండి',
    trainNumber: 'రైలు నంబర్',
    trainNumberPlaceholder: 'ఉదా., 12301',
    journeyDate: 'ప్రయాణ తేదీ',
    fromStation: 'ఎక్కడి నుండి',
    toStation: 'ఎక్కడికి',
    selectStation: 'స్టేషన్ ఎంచుకోండి',
    search: 'లభ్యత వెతకండి',
    searching: 'వెతుకుతోంది...',
    results: 'ఫలితాలు',
    chartStatus: 'చార్ట్ స్థితి',
    chartPrepared: 'చార్ట్ సిద్ధం',
    chartNotPrepared: 'చార్ట్ సిద్ధం కాలేదు',
    totalSeats: 'మొత్తం సీట్లు',
    vacant: 'ఖాళీ',
    occupied: 'నిండి',
    vacantBerths: 'ఖాళీ బెర్త్‌లు',
    coach: 'కోచ్',
    berth: 'బెర్త్',
    berthType: 'బెర్త్ రకం',
    from: 'నుండి',
    to: 'వరకు',
    trainRoute: 'రైలు మార్గం',
    favorites: 'ఇష్టాంశాలు',
    addToFavorites: 'ఇష్టాంశానికి చేర్చు',
    removeFromFavorites: 'ఇష్టాంశం తొలగించు',
    noFavorites: 'ఇష్టాంశాలు ఏవీ లేవు',
    noResults: 'ఫలితాలు లేవు',
    enterTrainNumber: 'రైలు నంబర్ ఇవ్వండి',
    selectStations: 'స్టేషన్లు ఎంచుకోండి',
    trainNotFound: 'రైలు కనుగొనబడలేదు',
    chartNotReady: 'చార్ట్ ఇంకా సిద్ధం కాలేదు',
    recentSearches: 'ఇటీవల వెతికినవి',
    availableClasses: 'అందుబాటులో ఉన్న తరగతులు',
    coachDetails: 'కోచ్ వివరాలు',
    lowerBerth: 'కింది',
    middleBerth: 'మధ్య',
    upperBerth: 'పైన',
    sideLower: 'సైడ్ కింది',
    sideUpper: 'సైడ్ పైన',
    day: 'రోజు',
    arrives: 'వచ్చే సమయం',
    departs: 'బయలుదేరే సమయం',
    boardingStation: 'ఎక్కే స్టేషన్',
    destinationStation: 'గమ్యం',
    language: 'భాష',
    settings: 'సెట్టింగ్‌లు',
    about: 'గురించి',
    version: 'సంస్కరణ 1.0.0',
    clearAll: 'అన్నీ తొలగించు',
};

// Bengali - বাংলা
const bn: typeof en = {
    appName: 'RailMitra',
    tagline: 'আপনার ট্রেন সহচর',
    searchTitle: 'খালি সিট খুঁজুন',
    trainNumber: 'ট্রেন নম্বর',
    trainNumberPlaceholder: 'যেমন, 12301',
    journeyDate: 'যাত্রার তারিখ',
    fromStation: 'কোথা থেকে',
    toStation: 'কোথায়',
    selectStation: 'স্টেশন বাছুন',
    search: 'প্রাপ্যতা খুঁজুন',
    searching: 'খুঁজছে...',
    results: 'ফলাফল',
    chartStatus: 'চার্ট স্থিতি',
    chartPrepared: 'চার্ট তৈরি',
    chartNotPrepared: 'চার্ট তৈরি হয়নি',
    totalSeats: 'মোট সিট',
    vacant: 'খালি',
    occupied: 'ভরা',
    vacantBerths: 'খালি বার্থ',
    coach: 'কোচ',
    berth: 'বার্থ',
    berthType: 'বার্থের ধরন',
    from: 'থেকে',
    to: 'পর্যন্ত',
    trainRoute: 'ট্রেনের রুট',
    favorites: 'পছন্দের',
    addToFavorites: 'পছন্দে যোগ করুন',
    removeFromFavorites: 'পছন্দ থেকে সরান',
    noFavorites: 'কোনো পছন্দ নেই',
    noResults: 'কোনো ফলাফল নেই',
    enterTrainNumber: 'ট্রেন নম্বর দিন',
    selectStations: 'স্টেশন নির্বাচন করুন',
    trainNotFound: 'ট্রেন পাওয়া যায়নি',
    chartNotReady: 'চার্ট এখনো তৈরি হয়নি',
    recentSearches: 'সাম্প্রতিক অনুসন্ধান',
    availableClasses: 'উপলব্ধ শ্রেণী',
    coachDetails: 'কোচের বিবরণ',
    lowerBerth: 'নিচের',
    middleBerth: 'মাঝের',
    upperBerth: 'উপরের',
    sideLower: 'সাইড নিচের',
    sideUpper: 'সাইড উপরের',
    day: 'দিন',
    arrives: 'আগমন',
    departs: 'প্রস্থান',
    boardingStation: 'ওঠার স্টেশন',
    destinationStation: 'গন্তব্য',
    language: 'ভাষা',
    settings: 'সেটিংস',
    about: 'সম্পর্কে',
    version: 'সংস্করণ 1.0.0',
    clearAll: 'সব মুছুন',
};

// Marathi - मराठी
const mr: typeof en = {
    appName: 'RailMitra',
    tagline: 'तुमचा ट्रेन मित्र',
    searchTitle: 'रिकाम्या सीट शोधा',
    trainNumber: 'ट्रेन क्रमांक',
    trainNumberPlaceholder: 'उदा., 12301',
    journeyDate: 'प्रवास तारीख',
    fromStation: 'कुठून',
    toStation: 'कुठे',
    selectStation: 'स्टेशन निवडा',
    search: 'उपलब्धता शोधा',
    searching: 'शोधत आहे...',
    results: 'निकाल',
    chartStatus: 'चार्ट स्थिती',
    chartPrepared: 'चार्ट तयार',
    chartNotPrepared: 'चार्ट तयार नाही',
    totalSeats: 'एकूण सीट',
    vacant: 'रिकामी',
    occupied: 'भरलेली',
    vacantBerths: 'रिकामे बर्थ',
    coach: 'डबा',
    berth: 'बर्थ',
    berthType: 'बर्थ प्रकार',
    from: 'कुठून',
    to: 'कुठे',
    trainRoute: 'ट्रेन मार्ग',
    favorites: 'आवडते',
    addToFavorites: 'आवडत्यात जोडा',
    removeFromFavorites: 'आवडत्यातून काढा',
    noFavorites: 'कोणतेही आवडते नाही',
    noResults: 'कोणताही निकाल नाही',
    enterTrainNumber: 'ट्रेन क्रमांक टाका',
    selectStations: 'स्टेशन निवडा',
    trainNotFound: 'ट्रेन सापडली नाही',
    chartNotReady: 'चार्ट अजून तयार नाही',
    recentSearches: 'अलीकडील शोध',
    availableClasses: 'उपलब्ध वर्ग',
    coachDetails: 'डबा तपशील',
    lowerBerth: 'खालचा',
    middleBerth: 'मधला',
    upperBerth: 'वरचा',
    sideLower: 'साइड खालचा',
    sideUpper: 'साइड वरचा',
    day: 'दिवस',
    arrives: 'आगमन',
    departs: 'निर्गमन',
    boardingStation: 'चढण्याचे स्टेशन',
    destinationStation: 'गंतव्य',
    language: 'भाषा',
    settings: 'सेटिंग्ज',
    about: 'माहिती',
    version: 'आवृत्ती 1.0.0',
    clearAll: 'सर्व साफ करा',
};

// Gujarati - ગુજરાતી
const gu: typeof en = {
    appName: 'RailMitra',
    tagline: 'તમારો ટ્રેન સાથી',
    searchTitle: 'ખાલી સીટ શોધો',
    trainNumber: 'ટ્રેન નંબર',
    trainNumberPlaceholder: 'દા.ત., 12301',
    journeyDate: 'મુસાફરી તારીખ',
    fromStation: 'ક્યાંથી',
    toStation: 'ક્યાં',
    selectStation: 'સ્ટેશન પસંદ કરો',
    search: 'ઉપલબ્ધતા શોધો',
    searching: 'શોધી રહ્યાં છે...',
    results: 'પરિણામો',
    chartStatus: 'ચાર્ટ સ્થિતિ',
    chartPrepared: 'ચાર્ટ તૈયાર',
    chartNotPrepared: 'ચાર્ટ તૈયાર નથી',
    totalSeats: 'કુલ સીટો',
    vacant: 'ખાલી',
    occupied: 'ભરેલી',
    vacantBerths: 'ખાલી બર્થ',
    coach: 'કોચ',
    berth: 'બર્થ',
    berthType: 'બર્થનો પ્રકાર',
    from: 'થી',
    to: 'સુધી',
    trainRoute: 'ટ્રેન માર્ગ',
    favorites: 'પસંદગીનું',
    addToFavorites: 'પસંદગીમાં ઉમેરો',
    removeFromFavorites: 'પસંદગીમાંથી દૂર કરો',
    noFavorites: 'કોઈ પસંદગી નથી',
    noResults: 'કોઈ પરિણામ નથી',
    enterTrainNumber: 'ટ્રેન નંબર દાખલ કરો',
    selectStations: 'સ્ટેશનો પસંદ કરો',
    trainNotFound: 'ટ્રેન મળી નથી',
    chartNotReady: 'ચાર્ટ હજુ તૈયાર નથી',
    recentSearches: 'તાજેતરની શોધ',
    availableClasses: 'ઉપલબ્ધ વર્ગો',
    coachDetails: 'કોચ વિગતો',
    lowerBerth: 'નીચેની',
    middleBerth: 'વચ્ચેની',
    upperBerth: 'ઉપરની',
    sideLower: 'સાઈડ નીચેની',
    sideUpper: 'સાઈડ ઉપરની',
    day: 'દિવસ',
    arrives: 'આગમન',
    departs: 'પ્રસ્થાન',
    boardingStation: 'ચડવાનું સ્ટેશન',
    destinationStation: 'ગંતવ્ય',
    language: 'ભાષા',
    settings: 'સેટિંગ્સ',
    about: 'વિશે',
    version: 'સંસ્કરણ 1.0.0',
    clearAll: 'બધું સાફ કરો',
};

// Kannada - ಕನ್ನಡ
const kn: typeof en = {
    appName: 'RailMitra',
    tagline: 'ನಿಮ್ಮ ರೈಲು ಗೆಳೆಯ',
    searchTitle: 'ಖಾಲಿ ಆಸನಗಳನ್ನು ಹುಡುಕಿ',
    trainNumber: 'ರೈಲು ಸಂಖ್ಯೆ',
    trainNumberPlaceholder: 'ಉದಾ., 12301',
    journeyDate: 'ಪ್ರಯಾಣ ದಿನಾಂಕ',
    fromStation: 'ಎಲ್ಲಿಂದ',
    toStation: 'ಎಲ್ಲಿಗೆ',
    selectStation: 'ನಿಲ್ದಾಣ ಆಯ್ಕೆ',
    search: 'ಲಭ್ಯತೆ ಹುಡುಕಿ',
    searching: 'ಹುಡುಕುತ್ತಿದೆ...',
    results: 'ಫಲಿತಾಂಶಗಳು',
    chartStatus: 'ಚಾರ್ಟ್ ಸ್ಥಿತಿ',
    chartPrepared: 'ಚಾರ್ಟ್ ಸಿದ್ಧ',
    chartNotPrepared: 'ಚಾರ್ಟ್ ಸಿದ್ಧವಾಗಿಲ್ಲ',
    totalSeats: 'ಒಟ್ಟು ಆಸನಗಳು',
    vacant: 'ಖಾಲಿ',
    occupied: 'ತುಂಬಿದ',
    vacantBerths: 'ಖಾಲಿ ಬರ್ತ್',
    coach: 'ಕೋಚ್',
    berth: 'ಬರ್ತ್',
    berthType: 'ಬರ್ತ್ ವಿಧ',
    from: 'ಇಲ್ಲಿಂದ',
    to: 'ಅಲ್ಲಿಗೆ',
    trainRoute: 'ರೈಲು ಮಾರ್ಗ',
    favorites: 'ಮೆಚ್ಚಿನವು',
    addToFavorites: 'ಮೆಚ್ಚಿನವುಗಳಿಗೆ ಸೇರಿಸಿ',
    removeFromFavorites: 'ಮೆಚ್ಚಿನವುಗಳಿಂದ ತೆಗೆದುಹಾಕಿ',
    noFavorites: 'ಮೆಚ್ಚಿನವುಗಳಿಲ್ಲ',
    noResults: 'ಫಲಿತಾಂಶಗಳಿಲ್ಲ',
    enterTrainNumber: 'ರೈಲು ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
    selectStations: 'ನಿಲ್ದಾಣಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
    trainNotFound: 'ರೈಲು ಸಿಗಲಿಲ್ಲ',
    chartNotReady: 'ಚಾರ್ಟ್ ಇನ್ನೂ ಸಿದ್ಧವಾಗಿಲ್ಲ',
    recentSearches: 'ಇತ್ತೀಚಿನ ಹುಡುಕಾಟಗಳು',
    availableClasses: 'ಲಭ್ಯ ವರ್ಗಗಳು',
    coachDetails: 'ಕೋಚ್ ವಿವರಗಳು',
    lowerBerth: 'ಕೆಳಗಿನ',
    middleBerth: 'ಮಧ್ಯ',
    upperBerth: 'ಮೇಲಿನ',
    sideLower: 'ಸೈಡ್ ಕೆಳಗಿನ',
    sideUpper: 'ಸೈಡ್ ಮೇಲಿನ',
    day: 'ದಿನ',
    arrives: 'ಆಗಮನ',
    departs: 'ನಿರ್ಗಮನ',
    boardingStation: 'ಹತ್ತುವ ನಿಲ್ದಾಣ',
    destinationStation: 'ಗಮ್ಯಸ್ಥಾನ',
    language: 'ಭಾಷೆ',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    about: 'ಬಗ್ಗೆ',
    version: 'ಆವೃತ್ತಿ 1.0.0',
    clearAll: 'ಎಲ್ಲಾ ತೆರವುಗೊಳಿಸಿ',
};

// Odia - ଓଡ଼ିଆ
const or: typeof en = {
    appName: 'ଏଠାରେ ମୋ ସିଟ୍',
    tagline: 'ଟ୍ରେନ ସିଟ୍ ଉପಲବ୍ଧତା',
    searchTitle: 'ଉପಲବ୍ଧ ସିଟ୍ ଖୋଜନ୍ତୁ',
    trainNumber: 'ଟ୍ରେନ ନମ୍ବର',
    trainNumberPlaceholder: 'ଯଥା, ୧୨୩୦୧',
    journeyDate: 'ଯାତ୍ରା ତାରିଖ',
    fromStation: 'ଷ୍ଟେସନରୁ',
    toStation: 'ଷ୍ଟେସନକୁ',
    selectStation: 'ଷ୍ଟେସନ ବାଛନ୍ତୁ',
    search: 'ଉପಲବ୍ଧତା ଖୋଜନ୍ତୁ',
    searching: 'ଖୋଜୁଛି...',
    results: 'ଫଳାଫଳ',
    chartStatus: 'ଚାର୍ଟ ସ୍ଥିତି',
    chartPrepared: 'ଚାର୍ଟ ପ୍ରସ୍ତୁତ',
    chartNotPrepared: 'ଚାର୍ଟ ପ୍ରସ୍ତୁତ ହୋଇନାହିଁ',
    totalSeats: 'ମୋଟ ସିଟ୍',
    vacant: 'ଖାଲି',
    occupied: 'ଭର୍ତ୍ତି',
    vacantBerths: 'ଖାଲି ବର୍ଥ',
    coach: 'କୋଚ',
    berth: 'ବର୍ଥ',
    berthType: 'ବର୍ଥ ପ୍ରକାର',
    from: 'ଠାରୁ',
    to: 'ପର୍ଯ୍ୟନ୍ତ',
    trainRoute: 'ଟ୍ରେନ ରୁଟ୍',
    favorites: 'ପସନ୍ଦ',
    addToFavorites: 'ପସନ୍ଦରେ ଯୋଡ଼ନ୍ତୁ',
    removeFromFavorites: 'ପସନ୍ଦରୁ ହଟାନ୍ତୁ',
    noFavorites: 'କୌଣସି ସେଭ୍ ହୋଇନାହିଁ',
    noResults: 'କିଛି ମିଳିଲା ନାହିଁ',
    enterTrainNumber: 'ଦୟାକରି ଟ୍ରେନ ନମ୍ବର ଦିଅନ୍ତୁ',
    selectStations: 'ଦୟାକରି ଷ୍ଟେସନ ବାଛନ୍ତୁ',
    trainNotFound: 'ଟ୍ରେନ ମିଳିଲା ନାହିଁ',
    chartNotReady: 'ଚାର୍ଟ ଏପର୍ଯ୍ୟନ୍ତ ପ୍ରସ୍ତୁତ ହୋଇନାହିଁ',
    recentSearches: 'ସାମ୍ପ୍ରତିକ ଖୋଜ',
    availableClasses: 'ଉପଲବ୍ଧ ଶ୍ରେଣୀ',
    coachDetails: 'କୋଚ ବିବରଣୀ',
    lowerBerth: 'ତଳ',
    middleBerth: 'ମଝି',
    upperBerth: 'ଉପର',
    sideLower: 'ପାଖ ତଳ',
    sideUpper: 'ପାଖ ଉପର',
    day: 'ଦିନ',
    arrives: 'ଆସିବ',
    departs: 'ଛାଡ଼ିବ',
    boardingStation: 'ଯାତ୍ରା ଆରମ୍ଭ',
    destinationStation: 'ଗନ୍ତବ୍ୟ',
    language: 'ଭାଷା',
    settings: 'ସେଟିଂସ୍',
    about: 'ବିଷୟରେ',
    version: 'ସଂସ୍କରଣ ୧.୦.୦',
    clearAll: 'ସବୁ ସଫା କରନ୍ତୁ',
};

export type Language = 'en' | 'hi' | 'ta' | 'te' | 'bn' | 'mr' | 'gu' | 'kn' | 'or';

export interface LanguageOption {
    code: Language;
    name: string;
    nativeName: string;
    shortLabel: string;
}

export const LANGUAGES: LanguageOption[] = [
    { code: 'en', name: 'English', nativeName: 'English', shortLabel: 'EN' },
    { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', shortLabel: 'हिं' },
    { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', shortLabel: 'த' },
    { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', shortLabel: 'తె' },
    { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', shortLabel: 'বাং' },
    { code: 'mr', name: 'Marathi', nativeName: 'मराठी', shortLabel: 'मरा' },
    { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', shortLabel: 'ગુ' },
    { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', shortLabel: 'ಕ' },
    { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', shortLabel: 'ଓ' },
];

const strings: Record<Language, typeof en> = { en, hi, ta, te, bn, mr, gu, kn, or };

let currentLanguage: Language = 'en';

export function setLanguage(lang: Language) {
    currentLanguage = lang;
}

export function getLanguage(): Language {
    return currentLanguage;
}

export function t(key: keyof typeof en): string {
    return strings[currentLanguage][key] || strings.en[key] || key;
}

export default { t, setLanguage, getLanguage };
